### ISSUE TITLE
GUI for gmhp

### ISSUE THREAD

**Issue by litheory** [anqurvanillapy/gmhp#1]
Have you considered creating a GUI for GmHp?It's not friedly for users who are not familiar with the Command-line tools.I'm learning Tkinter of python,maybe I‘ll  help to create the GUI if you do not have time.

**Comment by anqur** [comment]
GUI solution is not for now. You can think of a scenario that you use multiple clicks for picking directories, choosing target files and making confirmations if you are exactly an end-user? No. I assume that the users are basically the average coders using Markdown. So why bother creating GUI for some newcomers?

If you wanna take further steps, some enhancement can be done like creating a Markdown GUI editor that previews the generated slices in real time. If you're determined, do not fork and pull your request. Create your own repo instead. This project is to assume someone having a plain editor and tools for previewing their Markdown texts (or maybe not) to write their own stuff on desktop and preview manually.

You or I can consider a hot reload server for this. But as for a standalone editor for this, you should make your own attempt.
